# Generated by Django 3.1.2 on 2021-12-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=2000)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=50)),
                ('mobileno', models.DecimalField(decimal_places=0, max_digits=10)),
                ('address', models.TextField(default='')),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField(default=0)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
